name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pytest-html

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pytest pytest-html

      - name: Run tests and generate report
        run: |
          pytest test_library.py --html=report.html --self-contained-html

      - name: Upload test report as artifact
        if: always()  # Всегда загружает отчет, независимо от успеха или провала тестов
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}  # Выполняется только при успешном завершении тестов
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload code as artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
